#Función de creación de grafo con librería NetworkX. 
#Número de opciones de grafo: 4
import networkx as nx 

def crearGrafo(numGrafo):
    city = nx.Graph()
    if numGrafo == 0:
        city.add_node("Frankfurt", pos=(2,5))
        city.add_node("Bamberg", pos=(4,3))
        city.add_node("Culmbach", pos=(2,0))
        city.add_node("Hof", pos=(6,5))
        city.add_node("Gera", pos=(6,0))

        city.add_edge("Frankfurt", "Bamberg", weight=23)
        city.add_edge("Frankfurt", "Culmbach", weight=40)
        city.add_edge("Bamberg", "Hof", weight=38)
        city.add_edge("Bamberg", "Culmbach", weight=40)
        city.add_edge("Hof", "Gera", weight=12)
        city.add_edge("Gera", "Bamberg", weight=95)

    elif numGrafo == 1:
        city.add_node("nodo1", pos=(1,5))
        city.add_node("nodo2", pos=(1,3))
        city.add_node("nodo3", pos=(2,6))
        city.add_node("nodo4", pos=(2,2))
        city.add_node("nodo5", pos=(3,7))
        city.add_node("nodo6", pos=(3,4))
        city.add_node("nodo7", pos=(3,1))
        city.add_node("nodo8", pos=(4,6))
        city.add_node("nodo9", pos=(4,2))
        city.add_node("nodo10", pos=(5,5))
        city.add_node("nodo11", pos=(5,3))

        city.add_edge("nodo1", "nodo3", weight=5)
        city.add_edge("nodo1", "nodo6", weight=20)
        city.add_edge("nodo3", "nodo5", weight=7)
        city.add_edge("nodo5", "nodo6", weight=2)
        city.add_edge("nodo5", "nodo8", weight=12)
        city.add_edge("nodo6", "nodo10", weight=15)
        city.add_edge("nodo6", "nodo11", weight=6)
        city.add_edge("nodo10", "nodo11", weight=15)
        city.add_edge("nodo11", "nodo9", weight=5)
        city.add_edge("nodo9", "nodo7", weight=1)
        city.add_edge("nodo6", "nodo7", weight=9)
        city.add_edge("nodo7", "nodo4", weight=25)
        city.add_edge("nodo4", "nodo2", weight=4)
        city.add_edge("nodo2", "nodo6", weight=8)
    elif numGrafo == 2:
        city.add_node("Oradea", pos=(3,10))
        city.add_node("Zerind", pos=(2.5,9))
        city.add_node("Arad", pos=(2,8))
        city.add_node("Sibiu", pos=(4,7))
        city.add_node("Timisoara", pos=(2,5))
        city.add_node("Lugoj", pos=(3.5,4))
        city.add_node("Mehadia", pos=(3.5,3))
        city.add_node("Drobeta", pos=(3.5,2))
        city.add_node("Craiova", pos=(5,2))
        city.add_node("Rimnicu Vilcea", pos=(4.5,6))
        city.add_node("Fagaras", pos=(6,7))
        city.add_node("Bucharest", pos=(8,3))
        city.add_node("Pitesti", pos=(6,4))
        city.add_node("Giurgin", pos=(7.5,2))
        city.add_node("Urziceni", pos=(9,3.5))
        city.add_node("Vaslui", pos=(9.5,7))
        city.add_node("Iasi", pos=(9,8))
        city.add_node("Neamt", pos=(8,9))
        city.add_node("Hirsova", pos=(10,3.5))
        city.add_node("Eforie", pos=(10.5,4))

        city.add_edge("Oradea", "Zerind", weight=71)
        city.add_edge("Oradea", "Sibiu", weight=151)
        city.add_edge("Zerind", "Arad", weight=75)
        city.add_edge("Arad", "Sibiu", weight=140)
        city.add_edge("Arad", "Timisoara", weight=118)
        city.add_edge("Timisoara", "Lugoj", weight=111)
        city.add_edge("Lugoj", "Mehadia", weight=70)
        city.add_edge("Mehadia", "Drobeta", weight=75)
        city.add_edge("Drobeta", "Craiova", weight=111)
        city.add_edge("Sibiu", "Fagaras", weight=90)
        city.add_edge("Sibiu", "Rimnicu Vilcea", weight=80)
        city.add_edge("Rimnicu Vilcea", "Pitesti", weight=97)
        city.add_edge("Rimnicu Vilcea", "Craiova", weight=146)
        city.add_edge("Craiova", "Pitesti", weight=138)
        city.add_edge("Fagaras", "Bucharest", weight=211)
        city.add_edge("Pitesti", "Bucharest", weight=101)
        city.add_edge("Giurgin", "Bucharest", weight=90)
        city.add_edge("Bucharest", "Urziceni", weight=85)
        city.add_edge("Urziceni", "Vaslui", weight=92)
        city.add_edge("Vaslui", "Iasi", weight=92)
        city.add_edge("Iasi", "Neamt", weight=87)
        city.add_edge("Urziceni", "Hirsova", weight=98)
        city.add_edge("Eforie", "Hirsova", weight=86)
    else:
        city.add_node("A", pos=(2,5))
        city.add_node("B", pos=(2,0))
        city.add_node("C", pos=(4,5))
        city.add_node("D", pos=(6,5))
        city.add_node("E", pos=(4,3))

        city.add_edge("A", "C", weight=23)
        city.add_edge("A", "E", weight=40)
        city.add_edge("C", "D", weight=38)
        city.add_edge("D", "E", weight=40)
        city.add_edge("B", "A", weight=12)
        city.add_edge("B", "E", weight=95)
    return city 